---
title: "FW and ISt Combine"
author: "Lisa Vance"
date: "`r Sys.Date()`"
output: html_document
---

Code for combining Fremont Weir and I St stage data for inundation estimate

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Retrieve Fremont Weir and I St stage data from WDL:
   Select custom range - YBFMP monitoring starts 1998 and select through date range for publishing

  Fremont Weir(Station #A02170):
  https://wdl.water.ca.gov/WaterDataLibrary/StationDetails.aspx?Station=A02170&source=map

  I St(Station #A02100): https://wdl.water.ca.gov/WaterDataLibrary/StationDetails.aspx?Station=A02100&source=map

2. Packages
```{r setup, include=FALSE}
library(readr)
library(ggplot2)
library(lubridate)
library(rcompanion)
library(viridis)
library(dplyr)
library(ggthemes)
library(tidyverse)
library(rcartocolor)
library(tidylog)
```

3. Load files

```{r}

#WDL includes a lot of information at the top of the exported csv, skip for easier column headers 
FW <- read_csv("Working files/A02170_Stage_Daily_Mean.csv", skip =8)
ISt <- read_csv("Working files/A02100_Stage_Daily_Mean.csv", skip = 8)
```

4. Rename columns and adjust files for calculating estimated inundation at each sensor

```{r}

ISt <- ISt %>%
  rename(DateTime = 'Date Time',
         StageHeight_ISt = 'Stage Daily Mean (FOOT)',
         QualityCodeISt = 'Quality Code') %>%
  select(-c(QualityCodeISt))

FW <- FW %>%
  rename(DateTime = 'Date Time',
         StageHeight_FW = 'Stage Daily Mean (FOOT)',
         QualityCodeFW = 'Quality Code') %>%
  select(-c(QualityCodeFW))

StagesJoined <- FW %>%
  left_join(ISt, by = "DateTime")

str(StagesJoined)

#remove time from date so columns will match with LIS data

StagesJoined$Dates <- format(as.POSIXct(strptime(StagesJoined$DateTime,"%m/%d/%Y",tz="")) ,format = "%Y/%m/%d")

write_csv(StagesJoined, "StagesJoined.csv")

Inundation <- StagesJoined %>%
  mutate(Overtopping_FW = ifelse(StageHeight_FW >= 32, "Yes", "No"),
         Overtopping_ISt = ifelse(StageHeight_ISt >= 17, "Yes", "No")) %>%
  select(c(Dates, StageHeight_FW, Overtopping_FW, StageHeight_ISt, Overtopping_ISt))%>%
  mutate(Overtopping = case_when(Overtopping_FW == "Yes" ~ TRUE,
                                 Overtopping_ISt == "Yes" ~ TRUE, 
                                 Overtopping_FW == "No" ~ FALSE,
                                 Overtopping_ISt == "No" ~ FALSE))
  

#Write to csv for current data publishing period for use in both inundation dataset and drift data analysis

write_csv(Inundation, "Yolo Bypass Inundation 1998-2022.csv")

```

