---
title: "Inundation Data Combine"
author: "Haley"
date: "5/17/2021"
output: html_document
---

#Updated _____ L. Vance for updated data set

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load packages
```{r include=FALSE}
library(readr)
library(ggplot2)
library(lubridate)
library(rcompanion)
library(viridis)
library(dplyr)
library(ggthemes)
library(tidyverse)
library(rcartocolor) #for options, see: https://github.com/Nowosad/rcartocolor
library(tidylog)
```
#Load files
```{r}
LIS<- read_csv("LIS Daily Average 1998-2022.csv")
FW_Ist<-read_csv("Yolo Bypass Inundation 1998-2022.csv")
```
#Convert dates 
```{r}
LIS$Date<-mdy(LIS$Date)
FW_Ist$Date<-mdy(FW_Ist$Date)
```
#Combine
```{r}
All <- left_join(FW_Ist, LIS, 
              by = c("Dates"))

All <- All %>%
    mutate(Inundation = case_when(Overtopping_FW == "Yes" ~ TRUE,
                                 Overtopping_ISt == "Yes" ~ TRUE,
                                 Overtopping_LIS == "Yes" ~ TRUE,
                                 Overtopping_FW == "No" ~ FALSE,
                                 Overtopping_ISt == "No" ~ FALSE,
                                 Overtopping_LIS == "No" ~ FALSE)) %>%
  select(c(Dates, StageHeight_FW, Overtopping_FW, StageHeight_ISt, Overtopping_ISt, StageHeight_LIS, 
           Overtopping_LIS, Inundation))
```
#Export
```{r}
write.csv(All, "Yolo_Bypass_Inundation_1998-2022.csv")
```
######Convert dates to YYYY-MM-DD
#Read in file again
```{r}
setwd("Z:\\Useful Calculations!\\Inundation\\Working Files")
Inund<- read_csv("Yolo_Bypass_Inundation_1998-2022.csv")
```
#Convert dates to YYYY-MM-DD
```{r}
Inund$Date<- format(as.POSIXct(strptime(Inund$Date,"%m/%d/%Y",tz="")) ,format = "%Y/%m/%d")
Inund$Date<- as.Date(Inund$Date)
Inund$Date<-ymd(Inund$Date)
```
#Export
```{r}
setwd("Z:\\Useful Calculations!\\Inundation")
#write.csv(Inund, "Yolo_Bypass_Inundation1998-2021.csv",row.names = FALSE)
```
