---
title: "LIS Stage Daily Average"
author: "Haley"
date: "4/28/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Updated ____ L. Vance for updated dataset

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load packages
```{r include=FALSE}
library(readr)
library(ggplot2)
library(lubridate)
library(rcompanion)
library(viridis)
library(dplyr)
library(ggthemes)
library(tidyverse)
library(rcartocolor) #for options, see: https://github.com/Nowosad/rcartocolor
library(tidylog)
```

```{r}
LISStage <- read_csv("Working files/LIS Stage 2003-2022.csv")
LISStage98_02 <- read_csv("Working files/LIS Stage 1998-2002.csv")


#find any NA for stage or date
AnyNA <- filter(LISStage98_02, is.na(Stage))
AnyNA0 <- filter(LISStage, is.na(Stage))

NADate <- filter(LISStage, is.na(Date))   #76 values
NADate98_02 <- filter(LISStage98_02, is.na(Date)) #20 values

#there are 30 NA stage values from CDEC - notate later? 1998-2002
#1694 NA stage values 2003-2022

LISStage$Dates <- as.Date(LISStage$Date)
#updated column name since formatting is now similar to 1998-2002

LISStage98_02$Dates<- as.Date(LISStage98_02$Date)

#LISStage98_02$Dates<-ymd(LISStage98_02$Dates) doesnt seem needed to adjust
#LISStage$Date<-mdy(LISStage$Date)   seems to already be formatted simliar to the other file

str(LISStage)
str(LISStage98_02)
#all are in matching column types

#################################################################
#Haley - this was my lazy workaround to the date issue. one weird thing to note is they were all times in april or march at 2:00am
#make dataframe with NA dates to find problems
# new_DF <- LISStage[is.na(LISStage$Date),]
# 
# new <- LISStage98_02[is.na(LISStage98_02$Dates),]

#this step no longer seems necessary?
# #manually correct them
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "4/7/2002 2:00")] = as.Date("2002-04-07")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "4/6/2003 2:00")] = as.Date("2003-04-06")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "4/4/2004 2:00")] = as.Date("2004-04-04")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "4/3/2005 2:00")] = as.Date("2005-04-03")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "4/2/2006 2:00")] = as.Date("2006-04-02")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/11/2007 2:00")] = as.Date("2007-03-11")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/9/2008 2:00")] = as.Date("2008-03-09")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/8/2009 2:00")] = as.Date("2009-03-08")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/14/2010 2:00")] = as.Date("2010-03-14")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/13/2011 2:00")] = as.Date("2011-03-13")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/11/2012 2:00")] = as.Date("2012-03-11")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/10/2013 2:00")] = as.Date("2013-03-10")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/9/2014 2:00")] = as.Date("2014-03-09")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/8/2015 2:00")] = as.Date("2015-03-08")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/13/2016 2:00")] = as.Date("2016-03-13")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/12/2017 2:00")] = as.Date("2017-03-12")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/11/2018 2:00")] = as.Date("2018-03-11")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/10/2019 2:00")] = as.Date("2019-03-10")
# LISStage$Date[which(LISStage$`DATE / TIME (PST)` == "3/8/2020 2:00")] = as.Date("2020-03-08")

# #check to make sure they are all fixed
# new_DF2 <- LISStage[is.na(LISStage$Date),]

# #set stage to numeric - the problem you were having with the summarize code was due to the fact the stage height was assigned as a "character" instead of a number. to see what columns are classified as you can use the code: str(LISStage)
# LISStage$Stage <- as.numeric(LISStage$Stage)
# LISStage98_02$Stage <- as.numeric(LISStage98_02$Stage)
###################################################################################################
  
#FYI, there are some very large stage heights on some dates - may want to remove outliers before proceeding

DailyStage <- LISStage %>%
  group_by(Dates) %>%
  summarize(mean_Daily = mean(Stage))

#check for any NA values for stage height on dates - confirm if values existed on those dates

NADaily <- filter(DailyStage, is.na(mean_Daily))
#36 NA daily means - come back

DailyStage2 <- LISStage98_02 %>%
  group_by(Dates) %>%
  summarize(mean_Daily = mean(Stage))

#check for any NA values for stage hight on dates - confirm if values existed on those dates

NADaily2 <- filter(DailyStage2, is.na(mean_Daily))
#22 NA dailiy means - check dates

#####################################################
# #see how many NAs are returned
# new_DF3 <- DailyStage[is.na(DailyStage$mean_Daily),] #583 - seems reasonable for this long of a dataset
# #one NA in a day returns an NA for the whole daily average  

#There are 21 NAs returned for the 1998-2002 data
####################################################

#Eliminating Data Errors/ Outliers 
#Peak Stage of Record is 27.5 feet 
DailyStage <- DailyStage[which(DailyStage$mean_Daily <= 27.5),]
DailyStage2 <- DailyStage2[which(DailyStage2$mean_Daily <= 27.5),]

#removing data errors/outliers returns 0 NA, using peak stage of record as max
CheckNA <- filter(DailyStage, is.na(mean_Daily))
CheckNA2 <- filter(DailyStage2, is.na(mean_Daily))
```

```{r}
write.csv(DailyStage, "Daily Average 2003-2022.csv")
write.csv(DailyStage2, "Daily Average 1998-2002.csv")
```



